services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NEXT_PUBLIC_API_ENDPOINT: http://localhost:8081
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    user: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "todo_db"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
