openapi: 3.0.3
info:
  title: HUIT TODO api
  description: HUIT TODO アプリのAPI定義
  contact:
    url: https://twitter.com/shoumoji
  version: 1.0.0
tags:
  - name: todo
paths:
  /todo:
    post:
      tags:
        - todo
      summary: Add a new todo to the store
      description: Add a new todo to the store
      operationId: addTodo
      requestBody:
        description: Create a new todo in the store
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              example:
                content: "勉強会資料を作る"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "405":
          description: Invalid input
  /todo/{todo_id}:
    parameters:
      - name: todo_id
        in: path
        description: ID of todo to return
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - todo
      summary: Get a todo to the store
      description: Get a todo to the store
      operationId: getTodo
      requestBody:
        description: Get a todo in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Todo"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "405":
          description: Invalid input
    put:
      tags:
        - todo
      summary: Update a todo to the store
      description: Update a todo to the store
      operationId: updateTodo
      requestBody:
        description: Create a new todo in the store
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              example:
                content: "勉強会資料を作る"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "405":
          description: Invalid input
    delete:
      tags:
        - todo
      summary: Delete a todo to the store
      description: Delete a todo to the store
      operationId: deleteTodo
      responses:
        "204":
          description: Successful operation (No Content)
        "405":
          description: Invalid input
  /todo/list:
    get:
      tags:
        - todo
      summary: Get a todo list to the store
      description: Get a todo list to the store
      operationId: getTodoList
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Todo"
        "405":
          description: Invalid input

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        content:
          type: string
          description: content of todo list
          example: 勉強会の資料を作る
